version: '3.7'

networks:
  fly-net:
    external: true

services:
  main:
    build: .
    environment:
      TZ: Asia/Shanghai
      NODE_ENV: production
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/root/app/data
    networks:
      - fly-net
